In [2]:
import pandas as pd
import numpy as np

In [3]:
n2017_df = pd.read_csv('data/nba_season_2017.csv')
players_df = pd.read_csv('data/player_data.csv')

In [4]:
n2017_df.head(1)

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,2017.0,Alex Abrines,SG,23.0,OKC,68.0,6.0,1055.0,10.1,0.56,...,0.898,18.0,68.0,86.0,40.0,37.0,8.0,33.0,114.0,406.0

In [5]:
players_df.head(1)

,name,year_start,year_end,position,height,weight,birth_date,college
0,Alaa Abdelnaby,1991,1995,F-C,6-10,240.0,"June 24, 1968",Duke University

# INDTRODUCTION 

In this project, we'll work with data from the 2017 NBA Season (a pretty exciting one) to perform Data Wrangling techniques, and then some analysis.

We'll start by performing some Data Wrangling techniques to join the data from the season with that of players. We'll then perform different modifications and cleaning tasks to make sure our data is ready for analysis.

Finally, we'll perform some analysis using Group By and Transform operations.

## Data Wrangling Activities

### Merging the data
Let's start by merging the data from the season with player's data.

#### 1. Merge `n2017_df` and `players_df` with a left join

Merge `n2017_df` and `players_df` using a left outer join, that means, we want to have all the stats information, but if there are missing values that can't be matched from `players_df`, we want to set those season values as null.

Store the results from the merge in the variable `df`.

In [6]:
n2017_df.columns = n2017_df.columns.str.strip()
players_df.columns = players_df.columns.str.strip()

In [7]:
df = n2017_df.merge(players_df, how='left', left_on='Player', right_on='name')

In [8]:
df.head()

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,PF,PTS,name,year_start,year_end,position,height,weight,birth_date,college
0,2017.0,Alex Abrines,SG,23.0,OKC,68.0,6.0,1055.0,10.1,0.560,...,114.0,406.0,Alex Abrines,2017.0,2018.0,G-F,6-6,190.0,"August 1, 1993",NaN
1,2017.0,Quincy Acy,PF,26.0,TOT,38.0,1.0,558.0,11.8,0.565,...,67.0,222.0,Quincy Acy,2013.0,2018.0,F,6-7,240.0,"October 6, 1990",Baylor University
2,2017.0,Quincy Acy,PF,26.0,DAL,6.0,0.0,48.0,-1.4,0.355,...,9.0,13.0,Quincy Acy,2013.0,2018.0,F,6-7,240.0,"October 6, 1990",Baylor University
3,2017.0,Quincy Acy,PF,26.0,BRK,32.0,1.0,510.0,13.1,0.587,...,58.0,209.0,Quincy Acy,2013.0,2018.0,F,6-7,240.0,"October 6, 1990",Baylor University
4,2017.0,Steven Adams,C,23.0,OKC,80.0,80.0,2389.0,16.5,0.589,...,195.0,905.0,Steven Adams,2014.0,2018.0,C,7-0,255.0,"July 20, 1993",University of Pittsburgh

#### 2. Are there misses (mismatches) in the resulting dataframe?

As we performed a left outer join, if some values in from `n2017_df` couldn't be matched in `players_df`, the result will be null values (also referred as "misses" or "mismatches"). Are there any?

In [9]:
df['name'].isna().any()

np.True_

#### 3. How many rows couldn't be matched?

Based on previous activities consider `name` column to find how many misses were there in the resulting frame?

In [10]:
df['name'].isna().sum()

np.int64(4)

#### 4. Extract the names of the players that couldn't be matched

Extract the names of the players from `n2017_df` that couldn't be matched with `players_df` in a list (it must be a list), under the variable name `player_misses`.

In [11]:
df.loc[df['name'].isna()]

,Year,Player,Pos,Age,Tm,G,GS,MP,PER,TS%,...,PF,PTS,name,year_start,year_end,position,height,weight,birth_date,college
349,2017.0,Luc Mbah,SF,30.0,LAC,80.0,76.0,1787.0,10.3,0.581,...,122.0,484.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,2017.0,James Michael,PF,24.0,GSW,52.0,2.0,457.0,13.0,0.543,...,47.0,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,2017.0,Sheldon McClellan,SG,24.0,WAS,30.0,3.0,287.0,10.1,0.518,...,17.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,2017.0,Metta World,SF,37.0,LAL,25.0,2.0,160.0,6.2,0.380,...,18.0,57.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
player_misses = list(df.loc[df['name'].isna(), 'Player'].values)
player_misses

['Luc Mbah', 'James Michael', 'Sheldon McClellan', 'Metta World']

#### 5. Modify `players_df` with the correct names to re-try a successful merge

Now it's time to do some detective work...

We can guarantee that the players missing in `players_df` do exist, but they just have different names. Now, you must find the players discrepancies and update the names in the `players_df` dataframe.

For example, if in `n2017_df` the player's name was `"Michael J. Jordan"`, and in `players_df` it was just `"Michael Jordan"`, the task is to modify `players_df` to make it now `"Michael J. Jordan"`.

Important: Modify the `players_df` dataframe in place! If you "break" something, you can always read the data again.